# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2020 Carles Fernandez-Prades <carles.fernandez@cttc.es>
name: Simple CI

on:
  pull_request:
    paths-ignore:
      - '**/CITATION.cff'
  push:
    paths-ignore:
      - '**/CITATION.cff'

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: brew update && brew install ninja pkg-config hdf5 automake armadillo lapack gflags glog gnuradio log4cpp openssl pugixml protobuf && pip3 install mako
    - name: configure
      run: cd build && cmake -GNinja ..
    - name: build
      run: cd build && ninja -j 4
    - name: check
      run: cd build && ninja check && ../install/volk_gnsssdr_profile && ../install/run_tests
    - name: default position_test
      run: cd build && cmake -DENABLE_SYSTEM_TESTING_EXTRA=ON .. && ninja -j 4 && ../install/position_test


